public class Player {
    public void playing() {
        String player1Name = 'Muslera';
        String player2Name = 'Hagi';//! sift+alt ve aşağı yön tuşuna basarsak aşağı doğru kopyala yapıştır yapar.
        String player3Name = 'Pele';
        String player4Name = 'Alex';//! wrapın kısa yolu alt+z tuşudur.
        String player5Name = 'Maradona';
        System.debug('1. '+player1Name.toUpperCase() + ' İsminin Uzunluğu ' +player1Name.length());
        System.debug('2. '+player2Name + ' İsminin Uzunluğu '+ player2Name.length());
        System.debug('3. '+player3Name.toUpperCase() + ' İsminin Uzunluğu ' + player3Name.length());
        System.debug('4. '+player4Name + ' İsminin Uzunluğu '+ player4Name.length());
        System.debug('5. '+player5Name + ' İsminin Uzunluğu '+ player5Name.length());

    }
}